apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rh1-lb2075c-sat-lightspeed
  title: rh1-lb2075c-sat-lightspeed
  description: A hands on lab that delves into Red Hat Satellite features such as
    compliance monitoring and scanning, image mode, and vulnerability detection
    and remediation.
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: myee111
    ph.rhdp.io/owner: psrivast@redhat.com
    ph.rhdp.io/migrated-repo: https://github.com/rhpds/zt-satellite-lightspeed-install
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/rh1-lb2075c-sat-lightspeed
    ph.rhdp.io/created-at: 2026-09-03T05:14:45.857Z
  tags:
    - publishing-house
    - lab
    - rhdp-published
    - migration
  links:
    - url: https://github.com/rhpds/rh1-lb2075c-sat-lightspeed
      title: Repository
      icon: github
    - url: https://devspaces.apps.ocpv-infra02.wdc07.infra.demo.redhat.com#https://github.com/rhpds/rh1-lb2075c-sat-lightspeed
      title: Open in DevSpaces
      icon: catalog
    - url: https://central-api-publishing-house.apps.ocpv-infra02.wdc07.infra.demo.redhat.com
      title: Central
      icon: dashboard
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
