site_name: Installing Red Hat Lightspeed on Red Hat Satellite
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Introduction: modules/module-01-introduction.md
  - Module 2 - Install Lightspeed: modules/module-02-install-lightspeed.md
  - Module 3 - Configure Cve Data: modules/module-03-configure-cve-data.md
plugins:
- techdocs-core
