---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01-introduction
      label: "Introduction"
      solveButton: false
    - name: module-02-install-lightspeed
      label: "Install Red Hat Lightspeed"
      solveButton: false
    - name: module-03-configure-cve-data
      label: "Configure CVE Data and Verify Lightspeed"
      solveButton: false

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
    external: false
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel1.lab terminal"
    url: /wetty_rhel1/ssh/root
  - name: "rhel2.lab terminal"
    url: /wetty_rhel2/ssh/root
