---
- name: Validate module-02-install-lightspeed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Placeholder validate task
      ansible.builtin.debug:
        msg: "Validate automation not yet implemented for this module."
